# run the following command first:
# sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="ys"
ZSH_THEME="powerlevel10k/powerlevel10k"
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(common-aliases zsh-autosuggestions zsh-syntax-highlighting git svn)

# User configuration

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=C.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias zshconfig="vi ~/.zshrc"
alias ohmyzsh="vi ~/.oh-my-zsh"
alias zshreload="source ~/.zshrc"

alias vi="nvim"

alias zj="zellij -s"
alias za="zellij attach"
alias zl="zellij list-sessions"
alias zk="zellij kill-session"
alias zka="zellij kill-all-sessions"
alias zd="zellij delete-session"
alias zda="zellij delete-all-sessions"

alias cdw="cd ~/Workspace"
alias cdc="cd ~/Configs"
alias cdd="cd ~/Downloads"

# Set up $PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export HOME_LOCAL="$HOME/.local"
export PATH="$HOME_LOCAL/bin:$PATH"
# Homebrew
if [[ "$(uname)" == "Linux" ]]; then
  export BREW_HOME="/home/linuxbrew/.linuxbrew"
else
  export BREW_HOME="/opt/homebrew"
fi
if [ -d "$BREW_HOME" ]; then
  export PATH="$BREW_HOME/bin:$PATH"
fi
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
# Zellij
# Rust
export CARGO_HOME="$HOME/.cargo"
export PATH="$HOME/.cargo/bin:$PATH"
# Go
export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"

# Other env variables
export COLORTERM="truecolor"
